config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             class_name: "FormUser",
             controllers: {
               omniauth_callbacks: "omniauth_callbacks",
               registrations: "registrations",
             }

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.test?

  resources :identities, only: %i[index show] do
    member do
      get :show_sites
      post :toggle_feature
    end
    scope module: "identities" do
      resources :sites, only: %i[show update] do
        member do
          get :show_site
          post :add_widget
          post :remove_widget
          get :widget
          get :configure_site_config
          get :site_config
          get :stats
          get :stories
          get :portal
          get :demo_portal
          get :test_demo
        end
      end
    end
  end
  get "/identities/:identity_id/sites/:id/portal/*all" => "identities/sites#portal"

  resources :sites do
    scope module: "sites" do
      resources :stories do
        resources :contents
      end
    end
  end

  resource :widget_auth, only: :new

  authenticated :user do
    get "/", to: redirect("/identities")
    resources :accounts, only: %i[index show edit update] do
      member do
        post :promote_admin
        post :revoke_admin
        post :disconnect_facebook
      end
    end
  end

  get "/terms-of-service", to: "home#terms"
  get "/privacy-policy", to: "home#privacy"

  root to: "home#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :sites do
        get "/visit_count", to: "sites#visit_count"
        patch "/visit_count", to: "sites#update_visit_count"
        resources :stories, only: %i[index show create]
      end
    end
  end
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  has_many :sites, dependent: :destroy

  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }
  SUPPORTED_LOGIN_PROVIDERS = %i[square].freeze

  default_scope { where(is_active: true) }

  def self.find_for_oauth(auth) # rubocop:disable Metrics/AbcSize
    identity = find_by(provider: auth.provider, uid: auth.uid)
    identity = create(uid: auth.uid, provider: auth.provider) if identity.nil?
    identity.accesstoken = auth.credentials.token
    identity.refreshtoken = auth.credentials.refresh_token
    identity.name = auth.info.name
    identity.email = auth.info.email
    identity.nickname = auth.info.nickname
    identity.image = auth.info.image
    identity.phone = auth.info.phone
    identity.urls = (auth.info.urls || "").to_json
    identity.save
    identity
  end

  def email_placeholder
    "placeholder+#{provider}-#{uid}@swif.app"
  end
end

app/controllers/api/v1/sites/sites_controller.rb
module Api
  module V1
    module Sites
      class SitesController < BaseApiController
        def visit_count
          site = Site.find_by(domain: params[:domain])
          render json: { visit_count: site.visit_count } if site
        end

        def update_visit_count
          site = Site.find_by(domain: params[:domain])
          site.update!(visit_count: site.visit_count + 1)
          render json: { visit_count: site.visit_count } if site
        end
      end
    end
  end
end

app/controllers/api/v1/sites/stories_controller.rb
module Api
  module V1
    module Sites
      class StoriesController < BaseApiController
        before_action :authenticate_user, only: :create

        def index
          @stories = []
          Content.where(published: true).map do |content|
            @stories << content.story if content.story.site.reference_id == params[:site_id]
          end
          render status: :ok
        end

        def show
          @story = Story.find(params[:id])
        end

        def create
          site = Site.find_by(reference_id: create_params[:site_id])
          ActiveRecord::Base.transaction do
            @story = Story.create!(
              user_id: @current_user_id,
              site: site,
              story_title: create_params[:title],
            )
            Content.create!(
              story: @story,
              content_title: create_params[:title],
              url: create_params[:url],
              published: true,
              video_url: create_params[:url],
            )
          end

          render status: :created
        end

        private

        def create_params
          params.require(:story).permit(:site_id, :title, :url)
        end
      end
    end
  end
end

app/controllers/identities/sites_controller.rb
module Identities
  # rubcop:disable Metrics/AbcSize
  class SitesController < ApplicationController # rubocop:disable Metrics/ClassLength
    before_action :authenticate_user!, except: %i[widget site_config portal]
    before_action :set_identity, except: %i[widget site_config portal]
    before_action :set_site, only: %i[show site_config stats stories configure_site_config portal demo_portal]
    after_action :allow_iframe, only: %i[portal]

    def show
      @site = @identity.sites.where(reference_id: params[:id]).first
      render plain: "404 Not Found", status: :not_found unless @identity
      if Flipper[:user_nav].enabled?(FormUser.find(@identity.user_id))
        render "show_with_user_nav"
      else
        render
      end
    end

    def show_site # rubocop:disable Metrics/AbcSize
      if @identity
        @site = @identity.sites.where(reference_id: params[:id]).first

        client = @identity.user.square_client
        snippets_api = client.snippets
        result = snippets_api.retrieve_snippet(site_id: @site.reference_id)
        if result.success?
          @snippet = result.data.snippet
        elsif result.error?
          if result.errors[0][:code] == "NOT_FOUND"
            @alert = "SWiF snippet not installed"
          else
            @errors = result.errors
          end
        end
        render partial: "show_sites"
      else
        flash.now[:error] = "Not Found"
        render plain: "404 Not Found", status: :not_found
      end
    end

    def add_widget # rubocop:disable Metrics/AbcSize.
      if @identity
        @site = @identity.sites.find_by(reference_id: params[:id])
        client = @identity.user.square_client
        if defined? client
          snippets_api = client.snippets
          site_id = params[:id]
          body = {}
          body[:snippet] = {}
          # NOTE: not required as only 1 can be added to a site
          #       https://developer.squareup.com/docs/snippets-api/use-the-api#upsert-snippet
          # body[:snippet][:id] = 'snippet_'
          body[:snippet][:site_id] = params[:id]
          body[:snippet][:content] = <<~EO_SNIPPET_CONTENT
            <script>
              var SwifStaticConfig = (function(my){
                my.data = () => {
                  return #{ {
                    site: @site.reference_id,
                    identity: @identity.uid,
                  }.to_json}
                }#{' '}
                return(my)
              })(SwifStaticConfig || {})
            </script>
            <script defer src="#{widget_identity_site_url}"></script>
          EO_SNIPPET_CONTENT

          result = snippets_api.upsert_snippet(site_id: site_id, body: body)

          if result.success?
            flash[:info] = "Widget successfully added"
            # Rails.logger.debug result.data
          elsif result.error?
            flash[:info] = "Failed to add widget: #{result.errors}"
          end
        end
        redirect_to action: :show
      else
        flash.now[:error] = "Not Found"
        render plain: "404 Not Found", status: :not_found
      end
    end

    def remove_widget # rubocop:disable Metrics/AbcSize.
      if @identity
        client = @identity.user.square_client
        if defined? client
          snippets_api = client.snippets
          site_id = params[:id]
          result = snippets_api.delete_snippet(site_id: site_id)

          if result.success?
            flash[:info] = "Widget successfully removed"
            # Rails.logger.debug result.data
          elsif result.error?
            flash[:info] = "Failed to add widget: #{result.errors}"
          end
          flash[:info] = "Widget successfully removed"
        end
        redirect_to action: :show
      else
        flash.now[:error] = "Not Found"
        render plain: "404 Not Found", status: :not_found
      end
    end

    def update
      @site = @identity.sites.where(reference_id: params[:id]).first
      widget_config_overrides = widget_config_overrides_permitted_params.to_h.transform_values do |v|
        %w[true false].include?(v.downcase) ? eval(v.downcase) : v # rubocop:disable Security/Eval
      end
      @site.update!(widget_config_overrides: widget_config_overrides)
    end

    def configure_site_config
      @config = @site.widget_config
    end

    def site_config
      @config = @site.widget_config
    end

    def stats; end

    def stories; end

    def portal
      @config = @site.widget_config
      render layout: false
    end

    def demo_portal; end

    def widget
      redirect_to Webpacker.manifest.lookup!("widget_demo_svelte.js")
    end

    def test_demo
      @site = @identity.sites.where(reference_id: params[:id]).first
      @widget_snippet = <<~EO_SNIPPET_CONTENT
        <script>
          var SwifStaticConfig = (function(my){
            my.data = () => {
              return #{ {
                site: @site.reference_id,
                identity: @identity.uid,
              }.to_json}
            }#{' '}
            return(my)
          })(SwifStaticConfig || {})
        </script>
        <script defer src="#{widget_identity_site_url}"></script>
      EO_SNIPPET_CONTENT
    end

    private

    def set_identity
      @identity = current_user.identity_scope.find_by(uid: params[:identity_id])
    end

    def set_site
      @site = Site
              .where(identities: { uid: params[:identity_id] }, reference_id: params[:id])
              .joins(:identity)
              .first
    end

    def allow_iframe
      site = Site.find_by(reference_id: params[:id])
      response.headers.except! "X-Frame-Options"
      response.headers["Content-Security-Policy"] = "frame-ancestors 'self' #{site.domain} *.square.site *"
    end

    def widget_config_overrides_permitted_params
      params
        .require(:identity)
        .require(:site)
        .require(:widget_config_overrides)
        .permit!
    end
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorise_admin, only: [:toggle_feature]

  def index # rubocop:disable Metrics/AbcSize
    @identity = current_user.identities.where(provider: "square").first
    if @identity
      if @identity.sites && @identity.sites.active.length == 1
        redirect_to identity_site_path(@identity.uid, @identity.sites.active.first.reference_id)
      else
        redirect_to identity_path(@identity.uid)
      end
    elsif current_user.admin?
      @identities = Identity.all
    elsif current_user
      redirect_to sites_path
    else
      render plain: "404 Not Found", status: :not_found
    end
  end

  def show
    @identity = current_user.identity_scope.find_by(uid: params[:id])
    @sites = @identity.sites
    render plain: "404 Not Found", status: :not_found unless @identity
  end

  def toggle_feature
    form_user
    feature = Flipper[flipper_params]

    if feature.enabled?(form_user)
      feature.disable(form_user)
      action = "disabled"
    else
      feature.enable(form_user)
      action = "enabled"
    end

    flash[:notice] = "#{feature.to_s.humanize} successfully #{action}"

    redirect_to action: :show
  end

  def show_sites # rubocop:disable Metrics/AbcSize
    @identity = current_user.identity_scope.find_by(uid: params[:id])
    if @identity
      client = @identity.user.square_client
      if defined? client
        sites_api = client.sites
        result = sites_api.list_sites

        if result.success? && !result.data.nil?
          Site.find_or_update_by_api_result(@identity, result.data.sites)
        elsif result.error?
          flash[:errors] = result.errors
        end
        @sites = @identity.sites
      end
      render partial: "show_sites"
    else
      render plain: "404 Not Found", status: :not_found
    end
  end

  private

  def flipper_params
    params.require(:feature).to_sym
  end

  def form_user
    identity = current_user.identity_scope.find_by(uid: params[:id])
    identity.user.becomes(FormUser)
  end
end

app/controllers/sites/contents_controller.rb
module Sites
  class ContentsController < ApplicationController
    before_action :authenticate_user!

    def new
      @site = Site.find_by(reference_id: params[:site_id])
      @story = Story.find(params[:story_id])
      @content = Content.new
    end

    def create
      @story = Story.find(params[:story_id])
      Content.create!(content_params.merge(story: @story))

      flash[:info] = "Content successfully created"
      redirect_to edit_site_story_path(params[:site_id], story)
    end

    def edit
      @site = Site.find_by(reference_id: params[:site_id])
      @content = Content.find(params[:id])
      authorised_to_access!(@content, :manage)
    end

    def update
      @content = Content.find(params[:id])
      @content.update!(content_params)

      flash[:info] = "Content successfully updated"
      redirect_to edit_site_story_path(params[:site_id], story)
    end

    def destroy
      @content = Content.find(params[:id])
      authorised_to_access!(@content, :manage)

      @content.destroy!

      flash[:info] = "Content successfully deleted"
      redirect_to edit_site_story_path(params[:site_id], story)
    end

    private

    def content_params
      params.require(:content).permit(:story_id, :content_title, :url, :published, :video_url, :video,
                                      attachments: [],)
    end

    def story
      @story ||= Story.find(params[:story_id])
    end
  end
end

app/controllers/sites/stories_controller.rb
module Sites
  class StoriesController < ApplicationController
    before_action :authenticate_user!

    def index
      @site = Site.find_by(reference_id: params[:site_id])
      @stories = Story.where(user: current_user)
    end

    def new
      @site = Site.find_by(reference_id: params[:site_id])
      @story = Story.new
    end

    def create
      @site = Site.find_by(reference_id: params[:site_id])
      Story.create!(story_params.merge(site: @site, user: current_user))

      flash[:info] = "Story successfully created"
      redirect_to action: :index
    rescue ActiveRecord::RecordInvalid => e
      flash[:notice] = e.message
      render :new
    end

    def edit
      @site = Site.find_by(reference_id: params[:site_id])
      authorised_to_access!(story, :manage)
    end

    def update
      @site = Site.find_by(reference_id: params[:site_id])
      story.update!(story_params)

      flash[:info] = "Story successfully saved"
      redirect_to action: :index
    end

    def destroy
      authorised_to_access!(story, :manage)

      story.destroy!

      flash[:info] = "Story successfully deleted"
      redirect_to site_stories_path(params[:site_id])
    end

    private

    def story_params
      params.require(:story).permit(:site_id, :story_title, :published, :user_id, :story)
    end

    def story
      @story ||= Story.find(params[:id])
    end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Story.where(user: current_user).map(&:site)
  end

  def show; end
end

app/views/identities/sites/_show_site_actions.erb
<% if @snippet %>
  <div class="row">
    <div class="col">
      <%= link_to(
        "Remove snippet",
        remove_widget_identity_site_path,
        class: "btn btn-outline-danger",
        data: {
          method: :post,
          confirm: "Are you sure?"
        }
      ) %>
      <%= link_to(
        "Upsert snippet",
        add_widget_identity_site_path,
        class: "btn btn-primary",
        data: { method: :post }
      ) %>
    </div>
  </div>
<% end %>
<% if @alert || @errors %>
  <div class="row">
    <div class="col">
      <%= link_to(
        "Add snippet",
        add_widget_identity_site_path,
        class: "btn btn-primary",
        data: { method: :post }
      ) %>
    </div>
  </div>
<% end %>

app/views/identities/sites/_show_sites.html.erb
<% if @snippet %>
  <div class="row mt-3">
    <div class="col">
      <strong>status</strong>
    </div>
  </div>
  <div class="row">
    <div class="col">
      SWiF snippet installed 🎉
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <strong>created at</strong>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= DateTime.parse(@snippet[:created_at]).to_s(:long) %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <strong>updated at</strong>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= DateTime.parse(@snippet[:updated_at]).to_s(:long) %>
    </div>
  </div>
  <div class="row my-3">
    <div class="col">
      <strong>content</strong>
      <button
        class="btn"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#collapseSnippetContent"
        aria-expanded="false"
        aria-controls="collapseSnippetContent"
      >
        show snippet content
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col collapse" id="collapseSnippetContent">
      <pre class="word-wrap"><%= @snippet[:content] %></pre>
    </div>
  </div>
<% end %>
<% if @alert %>
  <div class="row mt-3">
    <div class="col">
      <strong>status</strong>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <pre><%= @alert %></pre>
    </div>
  </div>
<% end %>
<% if @errors %>
  <div class="row mt-3">
    <div class="col">
      <strong>errors</strong>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <pre><%= @errors %></pre>
    </div>
  </div>
<% end %>

<%= render partial: "show_site_actions" %>

app/views/identities/sites/_site_tabs.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <%= link_to(
        "Status",
        identity_site_path(identity_id: @identity.uid, id: @site.reference_id),
        aria: { current: :page },
        class: "nav-link #{action_name.to_sym == :show ? "active" : ""}"
    ) %>
  </li>
  <li class="nav-item">
    <%= link_to(
        "Config",
        configure_site_config_identity_site_path(identity_id: @identity.uid, id: @site.reference_id),
        aria: { current: :page },
        class: "nav-link #{action_name.to_sym == :configure_site_config ? "active" : ""}"
    ) %>
  </li>
  <li class="nav-item">
    <%= link_to(
        "Stats",
        stats_identity_site_path(identity_id: @identity.uid, id: @site.reference_id),
        aria: { current: :page },
        class: "nav-link #{action_name.to_sym == :stats ? "active" : ""}",
        data: { turbolinks: false }
    ) %>
  </li>
  <li class="nav-item">
    <%= link_to(
        "Stories",
        stories_identity_site_path(identity_id: @identity.uid, id: @site.reference_id),
        aria: { current: :page },
        class: "nav-link #{action_name.to_sym == :stories ? "active" : ""}",
        data: { turbolinks: false }
    ) %>
  </li>
  <% if Flipper[:portal].enabled?(FormUser.find(@identity.user_id))%>
    <li class="nav-item">
      <%= link_to(
          "Portal",
          demo_portal_identity_site_path(identity_id: @identity.uid, id: @site.reference_id),
          aria: { current: :page },
          class: "nav-link #{action_name.to_sym == :demo_portal ? "active" : ""}"
      ) %>
    </li>
  <% end %>
</ul>

app/views/identities/sites/configure_site_config.html.erb
<div class="container mt-3">
  <%= render partial: "identities/breadcrumbs" %>
  <%= render partial: "site_tabs" %>
  <%= form_for([:identity, @site], url: identity_site_path(identity_id: @identity.uid, id: @site.reference_id)) do |f| %>

    <% @config.map do |key, value| %>
      <div class="row g-3 align-items-center mb-3">
        <div class="col">
          <div class="form-group">
            <label for="identity_site_widget_config_overrides_<%= key %>">
              <%= key %>
            </label>
            <input
              type="text"
              class="form-control"
              value="<%= value %>"
              name="identity[site][widget_config_overrides][<%= key %>]"
              id="identity_site_widget_config_overrides_<%= key %>"
            />
          </div>
        </div>
      </div>
    <% end %>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
</ul>

app/views/identities/sites/demo_portal.html.erb
<div class="container mt-3">
  <%= render partial: "identities/breadcrumbs" %>
  <%= render partial: "site_tabs" %>
  <iframe
    frameBorder="0"
    style="height: 600px; width: 400px"
    title="portal"
    allow="camera;microphone"
    src="<%= portal_identity_site_url(@identity.uid, @site.reference_id) %>"
    class="content-iframe"
  />
</div>

app/views/identities/sites/messenger.html.erb
<%= content_tag(
  :div,
  "",
  data: {
    app: "messenger-app",
    identity: params[:identity_id],
    site: params[:id],
  }
)%>
<%= javascript_pack_tag "messenger_app" %>

app/views/identities/sites/portal.html.erb
<%= content_tag(
  :div,
  "",
  data: {
    app: "portal-app",
    identity: params[:identity_id],
    site: params[:id],
    config: @config,
  },
  style: "height:100%"
)%>
<%= javascript_pack_tag "portal_app" %>
<style>
body {
  margin: 0;
  overflow-y: hidden;
}
</style>

app/views/identities/sites/show.html.erb
<div class="container mt-3">
  <%= render partial: "identities/breadcrumbs" %>
  <div class="row card">
    <div class="card-body">
      <div class="card-title">
        <strong><%= @site.site_title %></strong>
      </div>
      <div>
        <%= @site.last_published %>
      </div>
      <div>
        <%= link_to "http://#{@site.domain}", target: "_blank" do %>
          <i class="fa fa-external-link-alt"></i>
          <%= "http://#{@site.domain}" %>
        <% end %>
      </div>
      <div class="row">
        <div
          data-controller="content-loader"
          data-content-loader-url-value="<%= show_site_identity_site_path(@identity.uid) %>"
        >
          <div class="text-center mt-3">
            <div class="spinner-border" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/identities/sites/show_with_user_nav.html.erb
<div class="container mt-3">
  <%= render partial: "identities/breadcrumbs" %>
  <%= render partial: "site_tabs" %>
  <ul class="list-group">
    <li class="list-group-item">
      <div class="row">
        <div class="col-lg-2 d-none d-lg-block">
          <strong>site title</strong>
        </div>
        <div class="col-lg-4 d-none d-lg-block">
          <strong>domain</strong>
        </div>
        <div class="col-lg-2 d-none d-lg-block">
          <strong>live</strong>
        </div>
        <div class="col-lg-2 d-none d-lg-block">
          <strong>created at</strong>
        </div>
        <div class="col-lg-2 d-none d-lg-block">
          <strong>updated at</strong>
        </div>
      </div>
      <% if @site %>
      <div class="row">
        <div class="col-lg-2">
          <strong class="d-lg-none">site title</strong>
          <%= @site.site_title %>
        </div>
        <div class="col-lg-4">
          <strong class="d-lg-none">domain</strong>
          <%= link_to "http://#{@site.domain}", "http://#{@site.domain}" %>
        </div>
        <div class="col-lg-2">
          <strong class="d-lg-none">live</strong>
          <%= @site.is_published %>
        </div>
        <div class="col-lg-2">
          <strong class="d-lg-none">created at</strong>
          <%= @site.created_at %>
        </div>
        <div class="col-lg-2">
          <strong class="d-lg-none">updated at</strong>
          <%= @site.updated_at %>
        </div>
      </div>
      <div
        data-controller="content-loader"
        data-content-loader-url-value="<%= show_site_identity_site_path(@identity.uid) %>"
      >
        <div class="text-center mt-3">
          <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </li>
</ul>

app/views/identities/sites/site_config.html.erb
<div class="container mt-3">
  <%= render partial: "identities/breadcrumbs" %>
  <%= render partial: "site_tabs" %>
  ability to configure coming soon ...
  <form>
    <% @config.map do |key, value| %>
      <div class="row g-3 align-items-center mb-3">
        <div class="col-auto">
          <input type="text" class="form-control" value="<%= key %>" disabled>
        </div>
        <div class="col-auto">
          <input type="text" class="form-control" value="<%= value %>" disabled>
        </div>
      </div>
    <% end %>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</ul>

app/views/identities/sites/test_demo.html.erb
<% content_for :head do %>
  <%= @widget_snippet.html_safe %>
<% end %>