config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             class_name: "FormUser",
             controllers: {
               omniauth_callbacks: "omniauth_callbacks",
               registrations: "registrations",
             }

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.test?

  resources :identities, only: %i[index show] do
    member do
      get :show_sites
      post :toggle_feature
    end
    scope module: "identities" do
      resources :sites, only: %i[show update] do
        member do
          get :show_site
          post :add_widget
          post :remove_widget
          get :widget
          get :configure_site_config
          get :site_config
          get :stats
          get :stories
          get :portal
          get :demo_portal
          get :test_demo
        end
      end
    end
  end
  get "/identities/:identity_id/sites/:id/portal/*all" => "identities/sites#portal"

  resources :sites do
    scope module: "sites" do
      resources :stories do
        resources :contents
      end
    end
  end

  resource :widget_auth, only: :new

  authenticated :user do
    get "/", to: redirect("/identities")
    resources :accounts, only: %i[index show edit update] do
      member do
        post :promote_admin
        post :revoke_admin
        post :disconnect_facebook
      end
    end
  end

  get "/terms-of-service", to: "home#terms"
  get "/privacy-policy", to: "home#privacy"

  root to: "home#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :sites do
        get "/visit_count", to: "sites#visit_count"
        patch "/visit_count", to: "sites#update_visit_count"
        resources :stories, only: %i[index show create]
      end
    end
  end
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  has_many :sites, dependent: :destroy

  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }
  SUPPORTED_LOGIN_PROVIDERS = %i[square].freeze

  default_scope { where(is_active: true) }

  def self.find_for_oauth(auth) # rubocop:disable Metrics/AbcSize
    identity = find_by(provider: auth.provider, uid: auth.uid)
    identity = create(uid: auth.uid, provider: auth.provider) if identity.nil?
    identity.accesstoken = auth.credentials.token
    identity.refreshtoken = auth.credentials.refresh_token
    identity.name = auth.info.name
    identity.email = auth.info.email
    identity.nickname = auth.info.nickname
    identity.image = auth.info.image
    identity.phone = auth.info.phone
    identity.urls = (auth.info.urls || "").to_json
    identity.save
    identity
  end

  def email_placeholder
    "placeholder+#{provider}-#{uid}@swif.app"
  end
end

app/controllers/identities/sites_controller.rb
module Identities
  # rubcop:disable Metrics/AbcSize
  class SitesController < ApplicationController # rubocop:disable Metrics/ClassLength
    before_action :authenticate_user!, except: %i[widget site_config portal]
    before_action :set_identity, except: %i[widget site_config portal]
    before_action :set_site, only: %i[show site_config stats stories configure_site_config portal demo_portal]
    after_action :allow_iframe, only: %i[portal]

    def show
      @site = @identity.sites.where(reference_id: params[:id]).first
      render plain: "404 Not Found", status: :not_found unless @identity
      if Flipper[:user_nav].enabled?(FormUser.find(@identity.user_id))
        render "show_with_user_nav"
      else
        render
      end
    end

    def show_site # rubocop:disable Metrics/AbcSize
      if @identity
        @site = @identity.sites.where(reference_id: params[:id]).first

        client = @identity.user.square_client
        snippets_api = client.snippets
        result = snippets_api.retrieve_snippet(site_id: @site.reference_id)
        if result.success?
          @snippet = result.data.snippet
        elsif result.error?
          if result.errors[0][:code] == "NOT_FOUND"
            @alert = "SWiF snippet not installed"
          else
            @errors = result.errors
          end
        end
        render partial: "show_sites"
      else
        flash.now[:error] = "Not Found"
        render plain: "404 Not Found", status: :not_found
      end
    end

    def add_widget # rubocop:disable Metrics/AbcSize.
      if @identity
        @site = @identity.sites.find_by(reference_id: params[:id])
        client = @identity.user.square_client
        if defined? client
          snippets_api = client.snippets
          site_id = params[:id]
          body = {}
          body[:snippet] = {}
          # NOTE: not required as only 1 can be added to a site
          #       https://developer.squareup.com/docs/snippets-api/use-the-api#upsert-snippet
          # body[:snippet][:id] = 'snippet_'
          body[:snippet][:site_id] = params[:id]
          body[:snippet][:content] = <<~EO_SNIPPET_CONTENT
            <script>
              var SwifStaticConfig = (function(my){
                my.data = () => {
                  return #{ {
                    site: @site.reference_id,
                    identity: @identity.uid,
                  }.to_json}
                }#{' '}
                return(my)
              })(SwifStaticConfig || {})
            </script>
            <script defer src="#{widget_identity_site_url}"></script>
          EO_SNIPPET_CONTENT

          result = snippets_api.upsert_snippet(site_id: site_id, body: body)

          if result.success?
            flash[:info] = "Widget successfully added"
            # Rails.logger.debug result.data
          elsif result.error?
            flash[:info] = "Failed to add widget: #{result.errors}"
          end
        end
        redirect_to action: :show
      else
        flash.now[:error] = "Not Found"
        render plain: "404 Not Found", status: :not_found
      end
    end

    def remove_widget # rubocop:disable Metrics/AbcSize.
      if @identity
        client = @identity.user.square_client
        if defined? client
          snippets_api = client.snippets
          site_id = params[:id]
          result = snippets_api.delete_snippet(site_id: site_id)

          if result.success?
            flash[:info] = "Widget successfully removed"
            # Rails.logger.debug result.data
          elsif result.error?
            flash[:info] = "Failed to add widget: #{result.errors}"
          end
          flash[:info] = "Widget successfully removed"
        end
        redirect_to action: :show
      else
        flash.now[:error] = "Not Found"
        render plain: "404 Not Found", status: :not_found
      end
    end

    def update
      @site = @identity.sites.where(reference_id: params[:id]).first
      widget_config_overrides = widget_config_overrides_permitted_params.to_h.transform_values do |v|
        %w[true false].include?(v.downcase) ? eval(v.downcase) : v # rubocop:disable Security/Eval
      end
      @site.update!(widget_config_overrides: widget_config_overrides)
    end

    def configure_site_config
      @config = @site.widget_config
    end

    def site_config
      @config = @site.widget_config
    end

    def stats; end

    def stories; end

    def portal
      @config = @site.widget_config
      render layout: false
    end

    def demo_portal; end

    def widget
      redirect_to Webpacker.manifest.lookup!("widget_demo_svelte.js")
    end

    def test_demo
      @site = @identity.sites.where(reference_id: params[:id]).first
      @widget_snippet = <<~EO_SNIPPET_CONTENT
        <script>
          var SwifStaticConfig = (function(my){
            my.data = () => {
              return #{ {
                site: @site.reference_id,
                identity: @identity.uid,
              }.to_json}
            }#{' '}
            return(my)
          })(SwifStaticConfig || {})
        </script>
        <script defer src="#{widget_identity_site_url}"></script>
      EO_SNIPPET_CONTENT
    end

    private

    def set_identity
      @identity = current_user.identity_scope.find_by(uid: params[:identity_id])
    end

    def set_site
      @site = Site
              .where(identities: { uid: params[:identity_id] }, reference_id: params[:id])
              .joins(:identity)
              .first
    end

    def allow_iframe
      site = Site.find_by(reference_id: params[:id])
      response.headers.except! "X-Frame-Options"
      response.headers["Content-Security-Policy"] = "frame-ancestors 'self' #{site.domain} *.square.site *"
    end

    def widget_config_overrides_permitted_params
      params
        .require(:identity)
        .require(:site)
        .require(:widget_config_overrides)
        .permit!
    end
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorise_admin, only: [:toggle_feature]

  def index # rubocop:disable Metrics/AbcSize
    @identity = current_user.identities.where(provider: "square").first
    if @identity
      if @identity.sites && @identity.sites.active.length == 1
        redirect_to identity_site_path(@identity.uid, @identity.sites.active.first.reference_id)
      else
        redirect_to identity_path(@identity.uid)
      end
    elsif current_user.admin?
      @identities = Identity.all
    elsif current_user
      redirect_to sites_path
    else
      render plain: "404 Not Found", status: :not_found
    end
  end

  def show
    @identity = current_user.identity_scope.find_by(uid: params[:id])
    @sites = @identity.sites
    render plain: "404 Not Found", status: :not_found unless @identity
  end

  def toggle_feature
    form_user
    feature = Flipper[flipper_params]

    if feature.enabled?(form_user)
      feature.disable(form_user)
      action = "disabled"
    else
      feature.enable(form_user)
      action = "enabled"
    end

    flash[:notice] = "#{feature.to_s.humanize} successfully #{action}"

    redirect_to action: :show
  end

  def show_sites # rubocop:disable Metrics/AbcSize
    @identity = current_user.identity_scope.find_by(uid: params[:id])
    if @identity
      client = @identity.user.square_client
      if defined? client
        sites_api = client.sites
        result = sites_api.list_sites

        if result.success? && !result.data.nil?
          Site.find_or_update_by_api_result(@identity, result.data.sites)
        elsif result.error?
          flash[:errors] = result.errors
        end
        @sites = @identity.sites
      end
      render partial: "show_sites"
    else
      render plain: "404 Not Found", status: :not_found
    end
  end

  private

  def flipper_params
    params.require(:feature).to_sym
  end

  def form_user
    identity = current_user.identity_scope.find_by(uid: params[:id])
    identity.user.becomes(FormUser)
  end
end

app/views/identities/_breadcrumbs.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <% if controller_name.to_sym == :identities && action_name.to_sym == :index %>
      <li class="breadcrumb-item active">
        Home
      </li>
    <% else %>
      <li class="breadcrumb-item">
        <%= link_to "Home", identities_path %>
      </li>
    <% end %>
    <% if controller_name.to_sym == :identities && action_name.to_sym == :show %>
      <li class="breadcrumb-item active">
        <%= @identity.name %>
      </li>
    <% elsif @identity%>
      <li class="breadcrumb-item">
        <%= link_to @identity.name, identity_path(@identity.uid) %>
      </li>
    <% end %>
    <% if controller_name.to_sym == :sites %>
      <li class="breadcrumb-item active">
        <%= @site&.site_title %>
      </li>
    <% end %>
  </ol>
</nav>

app/views/identities/_show_sites.erb
<ul class="list-group" data-testid="site-list">
  <% @sites.map do |site| %>
    <%= link_to identity_site_path(@identity.uid, site.reference_id), class: "list-group-item list-group-item-action" do %>
      <div class="row">
        <div>
          <strong><%= site.site_title %></strong>
        </div>
        <div>
          <%= site.last_published %>
        </div>
      </div>
    <% end %>
  <% end %>
</ul>
<br>
<%= link_to "Enable/Disable Portal", toggle_portal_identity_path(@identity.uid, portal: "portal"), class: "btn btn-primary", method: :post if current_user.user_actions&.dig("admin", "can_administer") %>

app/views/identities/_show_sites.html.erb
<ul class="list-group" data-testid="site-list">
  <% @sites.map do |site| %>
    <%= link_to identity_site_path(@identity.uid, site.reference_id), class: "list-group-item list-group-item-action" do %>
      <div class="row">
        <div>
          <strong><%= site.site_title %></strong>
        </div>
        <div>
          <%= site.last_published %>
        </div>
      </div>
    <% end %>
  <% end %>
</ul>
<br>
<div class="col-2">
  <% if current_user.admin? %>
    <% %i[portal user_nav].each do |feature| %>
      <%= link_to toggle_feature_identity_path(@identity.uid, feature: feature), method: :post do %>
        <% if !Flipper[feature].enabled?(FormUser.find(@identity.user_id)) %>
          <div class="btn btn-primary">
            Enable <%= feature.to_s.humanize %>
          </div>
        <% else %>
          <div class="btn btn-danger">
            Disable <%= feature.to_s.humanize %>
          </div>
        <% end %>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/identities/index.html.erb
<div class="container mt-3">
  <%= render partial: "identities/breadcrumbs" %>
  <ul class="list-group" data-testid="user-list">
    <% @identities.map do |identity| %>
      <%= link_to identity_path(identity.uid), class: "list-group-item list-group-item-action" do %>
        <div class="row">
          <div class="col-lg-4">
            <%= identity.uid %>
          </div>
          <div class="col-lg-2">
            <%= identity.name %>
          </div>
          <div class="col-lg-2">
          </div>
          <div class="col-lg-4">
          <%= "No sites yet" if identity.sites.empty? %>
          </div>
        </div>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/identities/show.html.erb
<div class="container mt-3" data-testid="sites-panel">
  <%= render partial: "identities/breadcrumbs" %>
  <h3>Your Sites</h3>
  <div
    data-controller="content-loader"
    data-content-loader-url-value="<%= show_sites_identity_path(@identity.uid) %>"
  >
    <%= render "show_sites" %>
    <div class="text-center mt-3">
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  </div>
</div>