config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             class_name: "FormUser",
             controllers: {
               omniauth_callbacks: "omniauth_callbacks",
               registrations: "registrations",
             }

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.test?

  resources :identities, only: %i[index show] do
    member do
      get :show_sites
      post :toggle_feature
    end
    scope module: "identities" do
      resources :sites, only: %i[show update] do
        member do
          get :show_site
          post :add_widget
          post :remove_widget
          get :widget
          get :configure_site_config
          get :site_config
          get :stats
          get :stories
          get :portal
          get :demo_portal
          get :test_demo
        end
      end
    end
  end
  get "/identities/:identity_id/sites/:id/portal/*all" => "identities/sites#portal"

  resources :sites do
    scope module: "sites" do
      resources :stories do
        resources :contents
      end
    end
  end

  resource :widget_auth, only: :new

  authenticated :user do
    get "/", to: redirect("/identities")
    resources :accounts, only: %i[index show edit update] do
      member do
        post :promote_admin
        post :revoke_admin
        post :disconnect_facebook
      end
    end
  end

  get "/terms-of-service", to: "home#terms"
  get "/privacy-policy", to: "home#privacy"

  root to: "home#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :sites do
        get "/visit_count", to: "sites#visit_count"
        patch "/visit_count", to: "sites#update_visit_count"
        resources :stories, only: %i[index show create]
      end
    end
  end
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :story
  has_many_attached :attachments
  has_one_attached :video

  def draft
    published ? "published" : "draft"
  end
end

app/models/user.rb
require "square"

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable, :omniauthable,
         omniauth_providers: %i[facebook square]

  has_many :identities, dependent: :destroy

  has_one_attached :avatar

  def generate_jwt
    JWT.encode(
      {
        id: id,
        exp: 60.days.from_now.to_i,
      },
      Rails.application.credentials.secret_key_base,
    )
  end

  def square
    identities.find_by(provider: "square")
  end

  def square_client
    @square_client ||= Square::Client.new(access_token: square.accesstoken)
  end

  def identity_scope
    admin? ? Identity : identities
  end

  def admin?
    user_actions&.dig("admin", "can_administer")
  end
end

app/controllers/sites/contents_controller.rb
module Sites
  class ContentsController < ApplicationController
    before_action :authenticate_user!

    def new
      @site = Site.find_by(reference_id: params[:site_id])
      @story = Story.find(params[:story_id])
      @content = Content.new
    end

    def create
      @story = Story.find(params[:story_id])
      Content.create!(content_params.merge(story: @story))

      flash[:info] = "Content successfully created"
      redirect_to edit_site_story_path(params[:site_id], story)
    end

    def edit
      @site = Site.find_by(reference_id: params[:site_id])
      @content = Content.find(params[:id])
      authorised_to_access!(@content, :manage)
    end

    def update
      @content = Content.find(params[:id])
      @content.update!(content_params)

      flash[:info] = "Content successfully updated"
      redirect_to edit_site_story_path(params[:site_id], story)
    end

    def destroy
      @content = Content.find(params[:id])
      authorised_to_access!(@content, :manage)

      @content.destroy!

      flash[:info] = "Content successfully deleted"
      redirect_to edit_site_story_path(params[:site_id], story)
    end

    private

    def content_params
      params.require(:content).permit(:story_id, :content_title, :url, :published, :video_url, :video,
                                      attachments: [],)
    end

    def story
      @story ||= Story.find(params[:story_id])
    end
  end
end

app/controllers/users/contents_controller.rb
module Users
  class ContentsController < ApplicationController
    before_action :authenticate_user!

    def new
      story
    end

    def create
      Content.create!(content_params)

      flash[:info] = "Content successfully created"
      redirect_to edit_user_story_path(current_user, story)
    end

    def edit
      @content = Content.find(params[:id])
      authorised_to_access!(@content, :manage)
    end

    def update
      @content = Content.find(params[:id])
      @content.update!(content_params)

      flash[:info] = "Content successfully updated"
      redirect_to edit_user_story_path(current_user, story)
    end

    def destroy
      @content = Content.find(params[:id])
      authorised_to_access!(@content, :manage)

      @content.destroy!

      flash[:info] = "Content successfully deleted"
      redirect_to edit_user_story_path(current_user, story)
    end

    private

    def content_params
      params.permit(:story_id, :content_title, :description, :url, :published, :video_url, :video, attachments: [])
    end

    def story
      @story ||= Story.find(params[:story_id])
    end
  end
end

app/controllers/users/stories_controller.rb
module Users
  class StoriesController < ApplicationController
    before_action :authenticate_user!

    def index
      @stories = Story.where(user: current_user)
    end

    def new
      @sites = Site.all
    end

    def create
      Story.create!(story_params)

      flash[:info] = "Story successfully created"
      redirect_to action: :index
    rescue ActiveRecord::RecordInvalid => e
      @sites = Site.all

      flash[:notice] = e.message
      render :new
    end

    def edit
      @sites = Site.all
      authorised_to_access!(story, :manage)
    end

    def update
      story.update!(story_params)

      flash[:info] = "Story successfully saved"
      redirect_to action: :index
    end

    def destroy
      authorised_to_access!(story, :manage)

      story.destroy!

      flash[:info] = "Story successfully deleted"
      redirect_to user_stories_path(current_user)
    end

    private

    def story_params
      params.permit(:site_id, :story_title, :published, :user_id)
    end

    def story
      @story ||= Story.find(params[:id])
    end
  end
end

app/views/users/contents/edit.html.erb
<div class="card" style="width: 100%;"  data-testid="contents-panel">
  <div class="card-header">
    <h4>Edit Content</h4>
  </div>

  <div class="card-body">
    <%= form_with url: user_story_content_path(current_user, @content.story, @content), method: :put, data: { testid: "content-form" } do |form| %>
      <div class="row g-3 align-items-center mb-3">
        <div class="col">
          <div class="form-group">
            <%= form.label :content_title, "Content title" %>
            <%= form.text_field :content_title, class: "form-control", type: "text", value: @content.content_title %>
          </div>

          <div class="form-group">
            <%= form.label :description, "Description" %>
            <%= form.text_field :description, class: "form-control", type: "text", value: @content.description %>
          </div>

          <div class="form-group">
            <%= form.label :url, "Url" %>
            <%= form.text_field :url, class: "form-control", type: "text", value: @content.url %>
          </div>

          <div class="form-group">
            <%= form.check_box :published, checked: @content.published %>
            <%= form.label :published, "Published" %>
          </div>

          <div class="form-group">
            <%= form.label :video_url %>
            <%= form.text_field :video_url, class: "form-control", value: @content.video_url %>
          </div>

          <div class="form-group">
            <%= form.label :video %>
              <%= form.file_field(
                :video,
                class: "form-control",
                data: {
                  action: "multi-upload#addFile"
                }
              ) %>
          </div>

          <%= form.submit "Submit", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/contents/new.html.erb
<div class="card" style="width: 100%;"  data-testid="contents-panel">
  <div class="card-header">
    <h4>New Content</h4>
  </div>

  <div class="card-body">
    <%= form_with url: user_story_contents_url(user_id: current_user.id, story_id: @story.id), data: { testid: "content-form" } do |form| %>
      <div class="row g-3 align-items-center mb-3">
        <div class="col">
          <div class="form-group">
            <%= form.label :content_title, "Content title" %>
            <%= form.text_field :content_title, class: "form-control", type: "text" %>
          </div>

          <div class="form-group">
            <%= form.label :description, "Description" %>
            <%= form.text_field :description, class: "form-control", type: "text" %>
          </div>

          <div class="form-group">
            <%= form.label :url, "Url" %>
            <%= form.text_field :url, class: "form-control", type: "text" %>
          </div>

          <div class="form-group">
            <%= form.check_box :published %>
            <%= form.label :published, "Published" %>
          </div>

          <div class="form-group">
            <%= form.label :video_url %>
            <%= form.text_field :video_url %>
          </div>

          <div class="form-group">
            <%= form.label :video %>
              <%= form.file_field(
                :video,
                multiple: true,
                class: "form-control",
                data: {
                  action: "multi-upload#addFile"
                }
              ) %>
          </div>

          <div data-controller="multi-upload">
            <div class="form-group attachments">
              <%= form.label :attachments %>
              <%= form.file_field(
                :attachments,
                multiple: true,
                class: "form-control",
                data: {
                  action: "multi-upload#addFile"
                }
              ) %>
            </div>

            <div data-multi-upload-target="files"></div>
          </div>

          <%= form.submit "Submit", class: "btn btn-primary mt-3" %>
        </div>
      </div>
    <% end %>
  </div>
</div>