config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             class_name: "FormUser",
             controllers: {
               omniauth_callbacks: "omniauth_callbacks",
               registrations: "registrations",
             }

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.test?

  resources :identities, only: %i[index show] do
    member do
      get :show_sites
      post :toggle_feature
    end
    scope module: "identities" do
      resources :sites, only: %i[show update] do
        member do
          get :show_site
          post :add_widget
          post :remove_widget
          get :widget
          get :configure_site_config
          get :site_config
          get :stats
          get :stories
          get :portal
          get :demo_portal
          get :test_demo
        end
      end
    end
  end
  get "/identities/:identity_id/sites/:id/portal/*all" => "identities/sites#portal"

  resources :sites do
    scope module: "sites" do
      resources :stories do
        resources :contents
      end
    end
  end

  resource :widget_auth, only: :new

  authenticated :user do
    get "/", to: redirect("/identities")
    resources :accounts, only: %i[index show edit update] do
      member do
        post :promote_admin
        post :revoke_admin
        post :disconnect_facebook
      end
    end
  end

  get "/terms-of-service", to: "home#terms"
  get "/privacy-policy", to: "home#privacy"

  root to: "home#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      namespace :sites do
        get "/visit_count", to: "sites#visit_count"
        patch "/visit_count", to: "sites#update_visit_count"
        resources :stories, only: %i[index show create]
      end
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorise_admin, only: %i[index show promote_admin revoke_admin]
  before_action :set_user, only: %i[show edit update promote_admin revoke_admin disconnect_facebook]

  def index
    @users = User.all.order(:email)
  end

  def show; end

  def edit; end

  def update
    if @user.update(account_params)
      redirect_to edit_account_path(params[:id]), notice: "Account successfully updated"
    else
      render :edit, status: :unprocessable_entity, alert: @user.errors.full_messages.inspect
    end
  end

  def promote_admin
    if @user.update(user_actions: { "admin" => { "can_administer" => true } })
      redirect_to accounts_path, notice: "Account successfully given admin priveledges"
    else
      redirect_to account_path(@user), alert: @user.errors.full_messages.inspect
    end
  end

  def revoke_admin
    if @user.update(user_actions: nil)
      redirect_to accounts_path, notice: "Account successfully revoked admin priveledges"
    else
      redirect_to account_path(@user), alert: @user.errors.full_messages.inspect
    end
  end

  def disconnect_facebook
    facebook_identity = @user.identities.find_by(provider: :facebook)
    if facebook_identity.update(is_active: false)
      redirect_to edit_account_path(@user), notice: "Facebook disconnected successfully"
    else
      redirect_to edit_account_path(@user), alert: facebook_identity.errors.full_messages.inspect
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def account_params
    params.fetch(:user, {}).permit(:avatar)
  end
end

app/views/accounts/edit.html.erb
<div class="container">
  <div class="col-lg-6 offset-lg-3">
    <%= simple_form_for(@user, url: account_path(@user) ) do |f| %>
      <%= f.input :avatar, label: "Avatar Image"%>
      <%= image_tag avatar_path(f.object), class: "rounded border shadow-sm d-block mx-auto my-3" %>
      <%= f.submit class: "btn btn-primary mt-3" %>
    <% end %>

    <div class="mt-3">
      <% if current_user.identities.where(provider: :facebook).empty? %>
        <%= link_to omniauth_authorize_path(FormUser, :facebook), class: "btn btn-primary", method: :post do %>
          <i class="fa fa-facebook-official"></i>
          <span class="align-self-center">connect Facebook</span>
        <% end %>
      <% else %>
        <%= link_to(
          disconnect_facebook_account_path(@user),
          class: "btn btn-outline-danger",
          data: {
            method: :post,
            confirm: "Are you sure?"
          }
        ) do %>
          <i class="fa fa-facebook-official"></i>
          <span class="align-self-center">dsiconnect Facebook</span>
        <% end %>
        currently connected as
        <%= current_user.identities.where(provider: :facebook).first.name %>
      <% end %>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="container mt-3">
  <h3>User List</h3>
  <ul class="list-group" data-testid="user-list">
    <% @users.each do |user| %>
      <div class="list-group-item list-group-item-action">
        <div class="row">
          <%= link_to account_path(user), class: "col-lg-8" do %>
            <%= user.identities.first&.name || user.email %>
          <% end %>
          <div class="col-lg-4">
            <strong><%= "CURRENT USER" if user.id == current_user.id %> </strong>
            <% if user.user_actions&.dig("admin", "can_administer") %>
              <%= link_to "Revoke Admin", revoke_admin_account_path(user), class: "btn btn-danger", method: :post unless current_user.id == user.id %>
            <% else %>
              <%= link_to "Promote to Admin", promote_admin_account_path(user), class: "btn btn-warning", method: :post %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container">
  <div class="col-lg-6 offset-lg-3">
		<%= simple_form_for(@user, url: account_path(@user) ) do |f| %>
			<%= image_tag avatar_path(f.object), class: "rounded border shadow-sm d-block mx-auto my-3" %>
			<%= f.input :email %>
		<% end %>
		<% if current_user.id != @user.id %>
			<% if @user.user_actions&.dig("admin", "can_administer") %>
				<hr>
				<strong >User is ADMIN</strong>
        <%= link_to "Revoke Admin", revoke_admin_account_path(@user), class: "btn btn-danger", method: :post unless current_user.id == @user.id %>
			<% else %>
				<hr>
        <%= link_to "Promote to Admin", promote_admin_account_path(@user), class: "btn btn-warning", method: :post %>
			<% end %>
		<% end %>
	</div>
</div>